server:
  port: ${PORT:8761}

eureka:
  instance:
    non-secure-port: ${PORT:8761}
    non-secure-port-enabled: true
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${PORT:8761}/eureka/